server:
   port: 8080
   servlet:
     context-path: /
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    static-path-pattern: /static/**/
  thymeleaf:
    #前缀
    prefix: classpath:/templates/
    #检测用户模板文件是否存在
    check-template-location: true
    #是否设置缓存
    cache: false
    #后缀
    suffix: .html
    #编码
    encoding: UTF-8
    servlet:
      content-type: text/html
    #页面模式
    mode: HTML5
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/db_dip_s?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#mybatis配置
mybatis:
  type-aliases-package: com.wpy.dips.bean
  mapper-locations: classpath:com/wpy/dips/dao/**/*.xml
#分页配置
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: false
  support-methods-arguments: true
  page-size-zero: true
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] === %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] === %msg%n'
    rolling-file-name: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
  level:
    root: info
  file:
    name: logger/mylog.log